import { Account} from "./account";
import {Group} from "./group";

export class Contact {
  id: number;
  lastName: string;
  firstName: string;
  street: string;
  place: string;
  postCode: string;
  country: string;
  mailbox: string;
  mailboxPlace: string;
  mailboxPostcode: string;
  mailboxCountry: string;
  phone: string;
  phone2: string;
  phone3: string;
  phone4: string;
  fax: string;
  email: string;
  email2: string;
  homepage: string;
  account1: Account;
  account2: Account;
  account3: Account;
  creatorID: string;
  editedByID: string;
  representativeID: string;
  additional: string;
  additional2: string;
  additional3: string;
  active: boolean;
  privatePerson: boolean;
  appellation: string;
  title: string;
  memo: number;
  department1: string;
  department2:string;
  department3: string;
  function1: string;
  function2: string;
  function3: string
  freeFlag1: boolean;
  freeFlag2: boolean;
  displayName: string;
  tradeFlag: boolean;
  productionFlag: boolean;
  serviceFlag: boolean;
  status: number;
  dsvFlag: boolean;
  dsvSourceOfData: string;
  dsvNotification: boolean;
  dsvDirectAdFlag: boolean;
  dsvAnonymised: boolean;
  dsvDataCollection: number;
  dsvAnonymisedBy: string;
  region: string;
  notes: string;
  createdDate: number;
  lastModifiedDate: number;
  group: Group;
}
